Improved dist targets. Added skeleton for install/uninstall targets.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -4,16 +4,16 @@
 #
 # Makefile for zinzong (for GNU/make)
 #
-# by Benjamin Gerard 
+# by Benjamin Gerard
 #
 
-SHELL      = /bin/sh
-srcdir    := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
-topdir    := $(abspath $(srcdir)/..)
-VPATH      = $(srcdir)
+SHELL	   = /bin/sh
+srcdir	  := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
+topdir	  := $(realpath $(srcdir)/..)
+VPATH	   = $(srcdir)
 PKGCONFIG  = pkg-config
-PACKAGE   := zingzong
-VERSION   := $(shell $(srcdir)/vcversion.sh || echo X)
+PACKAGE	  := zingzong
+VERSION	  := $(shell $(srcdir)/vcversion.sh || echo X)
 ifeq ($(VERSION),X)
 $(error vcversion.sh failed)
 endif
@@ -21,19 +21,21 @@ endif
 # ----------------------------------------------------------------------
 
 ifndef CFLAGS
-CFLAGS := -Wall
+CFLAGS := -Wall # -std=c99
 ifdef DEBUG
-CFLAGS += -O0 -g -DDEBUG=$(DEBUG)
+CFLAGS += -Og -g -DDEBUG=$(DEBUG)
 else
-CFLAGS += -O2
+CFLAGS += -Ofast -DNDEBUG=1
 endif
 endif
 
 # ----------------------------------------------------------------------
-#  libao (AO_CFLAGS="-DNO_AO" to disable)
+#  libao (NO_AO=1 to disable)
+# ----------------------------------------------------------------------
 
 ifeq ($(NO_AO),1)
 override AO_CFLAGS=-DNO_AO=1
+override AO_LIBS=
 endif
 
 ifndef AO_CFLAGS
@@ -49,7 +51,8 @@ AO_VERSION := $(shell $(PKGCONFIG) --modversion ao || echo n/a)
 endif
 
 # ----------------------------------------------------------------------
-#  samplerate (SRATE_CFLAGS="-DNO_SRATE" to disable)
+#  samplerate (NO_SRATE=1 to disable)
+# ----------------------------------------------------------------------
 
 # ifeq ($(NO_SRATE),1)
 # override SRATE_CFLAGS=-DNO_SRATE=1
@@ -67,7 +70,8 @@ endif
 # endif
 
 # ----------------------------------------------------------------------
-#  soxr (SOXR_CFLAGS="-DNO_SOXR" to disable)
+#  soxr (NO_SOXR=1 to disable)
+# ----------------------------------------------------------------------
 
 ifeq ($(NO_SOXR),1)
 override SOXR_CFLAGS=-DNO_SOXR=1
@@ -93,17 +97,16 @@ PACKAGE_CPPFLAGS  = \
 #override CPPFLAGS += -I$(srcdir)
 override CPPFLAGS += -I.
 
-original_CPPFLAGS := $(CPPFLAGS)
-original_CFLAGS   := $(CFLAGS)
-original_LDLIBS   := $(LDLIBS)
+org_CPPFLAGS := $(CPPFLAGS)
+org_CFLAGS   := $(CFLAGS)
+org_LDLIBS   := $(LDLIBS)
 
-
-zingzong_CPPFLAGS  = $(original_CPPFLAGS) $(PACKAGE_CPPFLAGS)
-zingzong_CFLAGS    = $(original_CFLAGS) $(AO_CFLAGS) $(SOXR_CFLAGS) 
-zingzong_LDLIBS    = $(original_LDLIBS) $(AO_LIBS) $(SOXR_LIBS)
+zz_CPPFLAGS  = $(org_CPPFLAGS) $(PACKAGE_CPPFLAGS)
+zz_CFLAGS    = $(org_CFLAGS) $(AO_CFLAGS) $(SOXR_CFLAGS)
+zz_LDLIBS    = $(org_LDLIBS) $(AO_LIBS) $(SOXR_LIBS)
 
 # ----------------------------------------------------------------------
-#  Build 
+#  Build
 # ----------------------------------------------------------------------
 
 all: zingzong
@@ -114,20 +117,20 @@ clean:
 
 .PHONY: clean
 
-zingzong: NAME     = zingzong
-zingzong: CPPFLAGS = $(zingzong_CPPFLAGS)
-zingzong: CFLAGS   = $(zingzong_CFLAGS)
-zingzong: LDLIBS   = $(zingzong_LDLIBS)
-
+zingzong: override NAME	    = zingzong
+zingzong: override CPPFLAGS = $(zz_CPPFLAGS)
+zingzong: override CFLAGS   = $(zz_CFLAGS)
+zingzong: override LDLIBS   = $(zz_LDLIBS)
 
 mix := mix_none mix_qerp mix_soxr
 out := out_ao out_raw
 vfs := vfs_file
-zz  := zz_bin zz_load zz_msg zz_play zz_str zz_vfs
+zz  := zz_bin zz_load zz_msg zz_play zz_str zz_vfs zz_mixers
 
-sources := $(addsuffix .c, $(zz) $(vfs) $(mix) $(out))
+sources := $(addsuffix .c,$(zz) $(vfs) $(mix) $(out))
 objects := $(sources:.c=.o)
 depends := $(sources:.c=.d)
+headers := zingzong.h zz_private.h mix_common.c
 
 zingzong: $(objects)
 
@@ -138,9 +141,15 @@ zingzong: $(objects)
 depend:
 .PHONY: depend
 
-%.d: %.c ; $(CC) $(CPPFLAGS) $(CFLAGS) -MM -MMD -c $<
+%.d: %.c ; $(CC) $(zz_CPPFLAGS) $(zz_CFLAGS) -MM -MMD -c $<
 
-ifneq ($(MAKECMDGOALS),clean)
+ifeq ($(words $(MAKECMDGOALS)),0)
+filtered = any word will do
+else
+filtered = $(filter-out clean% dist%,$(MAKECMDGOALS))
+endif
+
+ifneq ($(words $(filtered)),0)
 include $(depends)
 endif
 
@@ -151,15 +160,24 @@ endif
 dist_base := zingzong-$(VERSION)
 dist_arch := $(dist_base).tar.xz
 dist_list := \
+ $(addprefix src/,$(sources) $(headers) Makefile vcversion.sh) \
  LICENSE README.md \
- src/zingzong.c src/Makefile src/vcversion.sh \
  _build/build.sh
 
 dist: distrib
 distcheck: dist-check
+
 distrib: dist-arch
 
-dist-arch: $(dist_base)
+dist-base:
+	@test ! -d "$(dist_base)" || \
+	chmod -R -- u+w $(dist_base)/ && \
+	rm -rf -- $(dist_base)/
+	@mkdir -- "$(dist_base)" # Fail if exist or whatever
+
+.PHONY: 
+
+dist-arch: dist-base
 	@tar -C $(topdir) -cpf - $(dist_list) | tar -C $(dist_base) -xpf -
 	@echo $(VERSION) >$(dist_base)/VERSION
 	@echo $(VERSION) >$(dist_base)/src/VERSION
@@ -167,17 +185,62 @@ dist-arch: $(dist_base)
 	@rm -rf -- $(dist_base)
 	@echo "distrib file -- \"$(dist_arch)\" -- is ready"
 
-dist-check: dist
+dist-extract: dist-arch
 	@test ! -e $(dist_base) || { echo $(dist_base) already exist; false; }
 	@test ! -e _build-$(dist_base) || rm -rf -- _build-$(dist_base)
 	@tar xf $(dist_arch)
 	@chmod -R ug-w $(dist_base)/
-	@mkdir _build-$(dist_base)
-	@$(MAKE) -C _build-$(dist_base) -f ../$(dist_base)/src/Makefile all dist
-	@rm -rf -- _build-$(dist_base)/ $(dist_base)/
+	@echo "extracted -- \"$(dist_arch)\""
+
+dist-all: all distrib
+
+.IGNORE: dist-make	 # detect error on presence of _build-distbase
+dist-make: dist-extract
+	@mkdir -- _build-$(dist_base) && \
+	echo "compiling -- $(dist_base)" && \
+	$(MAKE) -sC _build-$(dist_base) \
+		-f ../$(dist_base)/src/Makefile dist-all && \
+	rm -rf -- _build-$(dist_base)
+
+dist-sweep:
+	@test ! -d $(dist_base) || \
+	chmod -R -- u+w $(dist_base) && rm -rf -- $(dist_base)
+	@test ! -d _build-$(dist_base) || {\
+		rm -rf -- _build-$(dist_base); \
+		echo "compilation of $(dist_base) has failed"; \
+		false; }
+
+dist-check: dist-make dist-sweep
+
+.PHONY: distcheck dist-check distrib dist
+.PHONY: dist-make dist-extract dist-arch dist-base
+
+# ----------------------------------------------------------------------
+#  Install / Uninstall
+# ----------------------------------------------------------------------
+
+INSTALL_EXEC   = $(error install not supported yet)
+INSTALL_DATA   = $(error install not supported yet)
+UNINSTALL_EXEC = $(error uninstall not supported yet)
+UNINSTALL_DATA = $(error uninstall not supported yet)
+
+install: install-exec install-data
+
+install-exec: zingzong
+	$(call INSTALL_EXEC $^)
+
+uninstall-exec: zingzong
+	$(call UNINSTALL_EXEC $^)
+
+install-data:
+	$(call INSTALL_DATA $^)
+
+.PHONY: install install-exec install-data
 
 
-$(dist_base):
-	@test ! -e "$@" || rm -r -- "$@" && mkdir -- "$@"
+uninstall: uninstall-exec uninstall-data
+	$(call INSTALL_EXEC $^)
 
-.PHONY: distcheck dist-check dist distrib dist-arch
+uninstall-exec uninstall-data:
+
+.PHONY: uninstall uninstall-exec uninstall-data
